Repository GoJip/gojip-server-v2, pull requests merged in 2024-03, with the labels that each got.

#5 [Feat/4] 체크리스트 좋아요 기능구현
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/like/controller/LikeController.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikeRequestDto.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikeResponseDto.java
  src/main/java/com/example/gojipserver/domain/like/entity/Like.java
  src/main/java/com/example/gojipserver/domain/like/repository/LikeRepository.java
  src/main/java/com/example/gojipserver/domain/like/service/LikeService.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
  src/main/java/com/example/gojipserver/domain/user/service/UserService.java
Labels: feat

#9 [Refactor/8] 토큰에러처리
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListResponseDto.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/CheckListRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/oauth2/controller/KakaoController.java
  src/main/java/com/example/gojipserver/domain/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/example/gojipserver/domain/oauth2/service/KakaoService.java
  src/main/java/com/example/gojipserver/global/config/SecurityConfig.java
  src/main/java/com/example/gojipserver/global/config/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/example/gojipserver/global/config/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/gojipserver/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/gojipserver/global/config/jwt/JwtTokenProvider.java
Labels: refactor

#14 [Feat/12] 좋아요 목록 조회
  src/main/java/com/example/gojipserver/domain/like/controller/LikeController.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikeGetResponseDto.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikePreviewResponseDto.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikeRequestDto.java
  src/main/java/com/example/gojipserver/domain/like/dto/LikeResponseDto.java
  src/main/java/com/example/gojipserver/domain/like/entity/Like.java
  src/main/java/com/example/gojipserver/domain/like/repository/LikeRepository.java
  src/main/java/com/example/gojipserver/domain/like/service/LikeService.java
Labels: feat

#16 [Feat/15] 체크리스트 구별조회
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListCityAllGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListCityCountGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListRecentResponseDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListResponseDto.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/CheckListRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/roomaddress/dto/RoomAddressSaveDto.java
  src/main/java/com/example/gojipserver/domain/roomaddress/entity/Coordinates.java
  src/main/java/com/example/gojipserver/domain/roomaddress/entity/RoomAddress.java
  src/main/java/com/example/gojipserver/domain/roomaddress/service/RoomAddressService.java
  src/main/java/com/example/gojipserver/domain/user/entity/User.java
Labels: feat

#20 [Feat/19] 특정 주소별 체크리스트 조회
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListSummaryGetDto.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/CheckListRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/like/controller/LikeController.java
  src/main/java/com/example/gojipserver/domain/roomaddress/dto/RoomAddressCheckListInfoDto.java
Labels: feat

#21 [Fix/18] 체크리스트 수정, 삭제 API
  src/main/java/com/example/gojipserver/domain/checklist/controller/CheckListController.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListRequestDto.java
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListUpdateDto.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/CheckList.java
  src/main/java/com/example/gojipserver/domain/checklist/entity/room/RoomStatusType.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/InnerOptionRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/ManagementCostOptionRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/NoiseRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/OuterOptionRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/repository/RoomStatusRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/repository/CheckListCollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/controller/CollectionController.java
  src/main/java/com/example/gojipserver/global/response/ApiResponse.java
Labels: feat, fix

#23 [Fix/22] 컬렉션 CRUD API 수정
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListRequestDto.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/entity/CheckListCollection.java
  src/main/java/com/example/gojipserver/domain/checklist_collection/repository/CheckListCollectionRepository.java
  src/main/java/com/example/gojipserver/domain/collection/controller/CollectionController.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionRequestDto.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionResponseDto.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionSaveDto.java
  src/main/java/com/example/gojipserver/domain/collection/dto/CollectionUpdateDto.java
  src/main/java/com/example/gojipserver/domain/collection/entity/Collection.java
  src/main/java/com/example/gojipserver/domain/collection/service/CollectionService.java
Labels: fix

#26 [Fix/24] 조회API 이미지, 평점 추가
  src/main/java/com/example/gojipserver/domain/checklist/repository/CheckListRepository.java
  src/main/java/com/example/gojipserver/domain/checklist/service/CheckListService.java
Labels: fix

#27 [fix/25] 체크리스트 단일 조회 DTO 변경
  src/main/java/com/example/gojipserver/domain/checklist/dto/CheckListOneGetDto.java
Labels: fix
